SET XACT_ABORT ON;

BEGIN TRANSACTION;

UPDATE TABLAOBS
SET TipoVenta = CASE
    WHEN CHARINDEX('RS', ISNULL(NotaTransaccion, '')) > 0 THEN 'IOC'
    ELSE 'OBS'
END
WHERE ISNULL(TipoVenta, '') <> CASE
    WHEN CHARINDEX('RS', ISNULL(NotaTransaccion, '')) > 0 THEN 'IOC'
    ELSE 'OBS'
END;

COMMIT TRANSACTION;
