/* Perfil completo para el área GERENCIA Y ADMINISTRACION (Área 6, Compañía 1). */
IF NOT EXISTS
(
    SELECT 1 FROM dbo.Area
    WHERE AreaId = 6 AND AreaNombre = 'GERENCIA Y ADMINISTRACION'
)
    THROW 50020, 'No se encontró el área esperada GERENCIA Y ADMINISTRACION (ID 6).', 1;
GO

DECLARE @Permisos varchar(max) =
'VENTAS.VER=1|VENTAS.POS=1|VENTAS.CAPTURAR=1|VENTAS.LISTA=1|VENTAS.OBS=1|VENTAS.GUIA_REMISION=1|VENTAS.NOTA_PEDIDO=1|VENTAS.RESUMEN_BOLETAS=1|VENTAS.ANULAR=1|CAJA.VER=1|CAJA.CONTROL=1|CAJA.APERTURA=1|CAJA.INFORME_FINAL=1|CAJA.CHICA=1|CAJA.GESTIONAR=1|COMPRAS.GESTIONAR=1|FACTURAS_SERVICIO.GESTIONAR=1|CLIENTES.GESTIONAR=1|CONTABILIDAD.VER=1|CONTABILIDAD.PDT_EMPRESA=1|CONTABILIDAD.ENVIO_FACTURAS=1|CONTABILIDAD.RESUMEN_BOLETAS=1|MANTENIMIENTO.VER=1|MANTENIMIENTO.AREAS=1|MANTENIMIENTO.CATEGORIAS=1|MANTENIMIENTO.PROVEEDORES=1|MANTENIMIENTO.FERIADOS=1|MANTENIMIENTO.COMPUTADORAS=1|MANTENIMIENTO.PRODUCTOS=1|MANTENIMIENTO.EMPLEADOS=1|MANTENIMIENTO.USUARIOS=1|MANTENIMIENTO.RESUMEN_BOLETAS=1|CONFIGURACION.VER=1|CONFIGURACION.FACTURACION=1|CONFIGURACION.VENTAS_BOLETAS=1|CONFIGURACION.CAJA=1|CONFIGURACION.PERMISOS=1';

EXEC dbo.usp_PermisoIndicador
    @Operacion = 'GUARDAR',
    @CompaniaId = 1,
    @AreaId = 6,
    @UsuarioId = NULL,
    @Permisos = @Permisos;
GO
